const SUPABASE_URL='https://bjxbqhcgdwmluwjfawse.supabase.co';const SUPABASE_KEY=window.SUPABASE_KEY||'';let db=null,session=null,profile=null,results=[],chart=null;const $=s=>document.querySelector(s);const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function init(){if(!SUPABASE_KEY)return;db=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);session=(await db.auth.getSession()).data.session;await auth();if($('#resultsGrid')||$('#marketSelect'))loadResults();if($('#posts'))loadForum();if($('#loginForm'))bindLogin();if($('#registerForm'))$('#registerForm').onsubmit=registerForm;db.auth.onAuthStateChange(async(_,s)=>{session=s;await auth();if($('#posts'))loadForum();});}
async function auth(){if(session){profile=(await db.from('profiles').select('username,role').eq('id',session.user.id).maybeSingle()).data;}document.querySelectorAll('[data-auth]').forEach(x=>x.textContent=session?(profile?.username||'Account'):'Login / Register');}
async function loadResults(){const r=await db.from('results').select('id,market_name,result_date,result_time,result_value').order('result_date',{ascending:false}).order('result_time',{ascending:false}).limit(200);results=r.data||[];if($('#resultsGrid'))renderResults();if($('#marketSelect')){const names=[...new Set(results.map(x=>x.market_name))];$('#marketSelect').innerHTML='<option value="">Select market</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('');$('#marketSelect').onchange=renderChart;renderChart();}}
function renderResults(){const q=($('#search')?.value||'').toLowerCase();const list=results.filter(x=>x.market_name.toLowerCase().includes(q));$('#resultsGrid').innerHTML=list.length?list.map(x=>`<article class="card"><h3>${esc(x.market_name)}</h3><div class="value">${esc(x.result_value)}</div><div class="muted">📅 ${esc(x.result_date)} &nbsp; ⏰ ${esc((x.result_time||'').slice(0,5))}</div></article>`).join(''):'<div class="empty">No published results found.</div>';if($('#search'))$('#search').oninput=renderResults;}
function renderChart(){if(!$('#chart')||!$('#marketSelect'))return;const market=$('#marketSelect').value;if(chart)chart.destroy();const rows=results.filter(x=>x.market_name===market).slice().reverse();if(!market||!rows.length){$('#chart').classList.add('hidden');$('#chartEmpty')?.classList.remove('hidden');return}$('#chart').classList.remove('hidden');$('#chartEmpty')?.classList.add('hidden');chart=new Chart($('#chart'),{type:'line',data:{labels:rows.map(x=>x.result_date),datasets:[{label:market,data:rows.map(x=>Number(String(x.result_value).replace(/[^0-9.-]/g,''))),tension:.3,borderWidth:2}]},options:{responsive:true,plugins:{legend:{display:false}}}})}
async function loadForum(){const r=await db.from('forum_posts').select('id,title,body,created_at,user_id,profiles(username)').order('created_at',{ascending:false}).limit(50);const posts=r.data||[];$('#posts').innerHTML=posts.length?posts.map(p=>`<article class="post"><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p><small>By ${esc(p.profiles?.username||'User')} · ${new Date(p.created_at).toLocaleString()}</small><div class="actions"><button class="secondary" onclick="comments(${p.id})">Comments</button>${profile?.role==='admin'?` <button class="secondary" onclick="delPost(${p.id})">Delete</button>`:''}</div></article>`).join(''):'<div class="empty">No forum posts yet. Register to start a discussion.</div>';}
function modal(html){const m=$('#modal');if(!m)return;$('#modalContent').innerHTML=html;m.classList.remove('hidden');$('#closeModal').onclick=()=>m.classList.add('hidden');}
async function comments(id){const p=await db.from('forum_posts').select('title').eq('id',id).single();const c=await db.from('forum_comments').select('body,created_at,profiles(username)').eq('post_id',id).order('created_at');modal(`<h2>${esc(p.data?.title||'Discussion')}</h2>${(c.data||[]).map(x=>`<p><b>${esc(x.profiles?.username||'User')}</b> ${esc(x.body)}</p>`).join('')||'<p class="muted">No comments yet.</p>'}${session?`<form id="commentForm"><textarea id="commentBody" required placeholder="Write a comment..."></textarea><button class="primary">Comment</button></form>`:'<p class="muted">Login to comment.</p>'}`);if(session)$('#commentForm').onsubmit=async e=>{e.preventDefault();const r=await db.from('forum_comments').insert({post_id:id,user_id:session.user.id,body:$('#commentBody').value.trim()});if(r.error)alert(r.error.message);else comments(id);};}
async function delPost(id){if(profile?.role!=='admin')return;await db.from('forum_posts').delete().eq('id',id);loadForum();}
function bindLogin(){$('#loginForm').onsubmit=async e=>{e.preventDefault();const r=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(r.error)alert(r.error.message);else location.href='index.html';};}
async function registerForm(e){e.preventDefault();const u=$('#username').value.trim(),email=$('#email').value.trim(),password=$('#password').value;const r=await db.auth.signUp({email,password,options:{data:{username:u}}});if(r.error){alert(r.error.message);return}if(r.data.user)await db.from('profiles').update({username:u}).eq('id',r.data.user.id);alert(r.data.session?'Registration successful.':'Registration successful. Check your email to verify your account.');location.href='login.html';}
async function newPost(){if(!session){location.href='register.html';return}modal(`<h2>Create forum post</h2><form id="postForm"><input id="title" required maxlength="120" placeholder="Title"><textarea id="body" required maxlength="5000" placeholder="Write your discussion..."></textarea><button class="primary">Post</button></form>`);$('#postForm').onsubmit=async e=>{e.preventDefault();const r=await db.from('forum_posts').insert({user_id:session.user.id,title:$('#title').value.trim(),body:$('#body').value.trim()});if(r.error)alert(r.error.message);else location.reload();};}
window.comments=comments;window.delPost=delPost;document.addEventListener('DOMContentLoaded',()=>{init();$('#newPostBtn')?.addEventListener('click',newPost);});