const SUPABASE_URL='https://bjxbqhcgdwmluwjfawse.supabase.co';
const SUPABASE_KEY=window.SUPABASE_KEY||'';
let db=null,results=[],session=null,chart=null;
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function showModal(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}function closeModal(){$('#modal').classList.add('hidden')}$('#closeModal').onclick=closeModal;
function setup(){if(!SUPABASE_KEY){$('#adminStatus').textContent='Supabase key not configured yet. Add the publishable key in config.js.';return}db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);db.auth.onAuthStateChange(()=>authState());authState();load()}
async function load(){if(!db)return;const r=await db.from('results').select('*').order('result_date',{ascending:false}).limit(100);results=r.data||[];renderResults();renderMarkets();renderChart();const p=await db.from('forum_posts').select('id,title,body,created_at,profiles(username)').order('created_at',{ascending:false}).limit(30);renderPosts(p.data||[]);if(results[0]){$('#latestValue').textContent=results[0].result_value;$('#latestMeta').textContent=`${results[0].market_name} · ${results[0].result_date}`}}
function renderResults(){const q=($('#search').value||'').toLowerCase();const list=results.filter(x=>x.market_name.toLowerCase().includes(q));$('#resultsGrid').innerHTML=list.length?list.map(x=>`<article class="card"><h3>${esc(x.market_name)}</h3><div class="value">${esc(x.result_value)}</div><span class="muted">${esc(x.result_date)}</span></article>`).join(''):'<div class="empty">No published results found.</div>'}
function renderMarkets(){const names=[...new Set(results.map(x=>x.market_name))];$('#marketSelect').innerHTML='<option value="">Select market</option>'+names.map(n=>`<option>${esc(n)}</option>`).join('')}
function renderChart(){const market=$('#marketSelect').value;if(chart){chart.destroy();chart=null}const rows=results.filter(x=>x.market_name===market).slice().reverse();if(!market||!rows.length){$('#chart').classList.add('hidden');$('#chartEmpty').classList.remove('hidden');return}$('#chart').classList.remove('hidden');$('#chartEmpty').classList.add('hidden');chart=new Chart($('#chart'),{type:'line',data:{labels:rows.map(x=>x.result_date),datasets:[{label:market,data:rows.map(x=>Number(x.result_value)),tension:.3}]},options:{responsive:true,plugins:{legend:{display:false}}}})}
function renderPosts(posts){$('#posts').innerHTML=posts.length?posts.map(p=>`<article class="post"><h3>${esc(p.title)}</h3><p>${esc(p.body)}</p><small>By ${esc(p.profiles?.username||'User')} · ${new Date(p.created_at).toLocaleString()}</small></article>`).join(''):'<div class="empty">No forum posts yet. Sign in to start the discussion.</div>'}
async function authState(){if(!db)return;const r=await db.auth.getSession();session=r.data.session;$('#authBtn').textContent=session?'Logout':'Login';if(session){const p=await db.from('profiles').select('role,username').eq('id',session.user.id).maybeSingle();if(p.data?.role==='admin'){$('#admin').classList.remove('hidden');$('#adminStatus').textContent=`Signed in as admin: ${p.data.username}`}}}
$('#authBtn').onclick=async()=>{if(!db)return alert('Supabase is not configured yet.');if(session){await db.auth.signOut();location.reload();return}showModal(`<h2>Login</h2><form id="loginForm"><input id="email" type="email" placeholder="Email" required><input id="password" type="password" placeholder="Password" required><button class="primary">Login</button><p class="muted">New user? <a href="#" id="signupLink">Create account</a></p></form>`);$('#loginForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});if(error)return alert(error.message);closeModal();location.reload()};$('#signupLink').onclick=e=>{e.preventDefault();showModal(`<h2>Create account</h2><form id="signupForm"><input id="email" type="email" placeholder="Email" required><input id="username" placeholder="Username" required><input id="password" type="password" minlength="6" placeholder="Password" required><button class="primary">Register</button></form>`);$('#signupForm').onsubmit=async e=>{e.preventDefault();const {data,error}=await db.auth.signUp({email:$('#email').value,password:$('#password').value});if(error)return alert(error.message);if(data.user){const r=await db.from('profiles').insert({id:data.user.id,username:$('#username').value});if(r.error)return alert(r.error.message)}alert('Account created.');closeModal()}}};
$('#newPostBtn').onclick=()=>{if(!session)return $('#authBtn').click();showModal(`<h2>New forum post</h2><form id="postForm"><input id="title" placeholder="Title" required><textarea id="body" placeholder="Write your post..." required></textarea><button class="primary">Publish</button></form>`);$('#postForm').onsubmit=async e=>{e.preventDefault();const {error}=await db.from('forum_posts').insert({user_id:session.user.id,title:$('#title').value,body:$('#body').value});if(error)return alert(error.message);closeModal();load()}};
$('#resultForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await db.from('results').upsert({market_name:f.get('market'),result_date:f.get('date'),result_value:f.get('value')},{onConflict:'market_name,result_date'});if(error)return alert(error.message);e.target.reset();load()};$('#search').oninput=renderResults;$('#marketSelect').onchange=renderChart;setup();